### ISSUE TITLE
undefined method `blueprint'

### ISSUE THREAD

**Issue by juliocesar** [nmerouze/machinist_mongo#10]
Hey all,

I'm trying to get machinist_mongo (HEAD from machinist2 branch) to work with mongoid 2.0.0.beta.19.  This is not a Rails app by the way.

I've required machinist_mongo like so in my Gemfile (using Bundler 1.0.2):

```
gem 'machinist_mongo',  
  :require => 'machinist/mongoid', 
  :git => 'http://github.com/nmerouze/machinist_mongo.git',
  :branch => 'machinist2'
```

And my spec_helper looks like this

```
require File.dirname(__FILE__) + '/../config/boot'
require 'rspec'
require 'machinist'
require 'machinist/mongoid'

RSpec.configure do |config|
  config.before(:each) { Machinist.reset_before_test }
end

Store.blueprint do
  name        { Faker::Company.name }
  email       { Faker::Internet.email }
  description { Faker::Lorem.paragraph(1 + rand(3)) }
  location    { Faker::Address.street_address }
end
```

Any ideas? Is the machinist2 branch working at all?

Thanks!

**Comment by juliocesar** [comment]
Nevermind. Apparently Bundler's require order was somehow screwing things up. Sorry!
